import fs from "fs";
import path from "path";

const DATA_PATH = path.join(
  process.cwd(),
  "public/data/WarframeUsageData2025.json",
);
const OUTPUT_PATH = path.join(process.cwd(), "src/constants/mrWeights.ts");

function solveWeights() {
  const data = JSON.parse(fs.readFileSync(DATA_PATH, "utf8"));
  const allData = data["ALL"];

  // Collect all items across all categories (Warframe, Primary, Secondary, Melee, etc.)
  const items: { global: number; mr: number[] }[] = [];

  for (const category in allData) {
    const categoryData = allData[category];
    for (const itemName in categoryData) {
      const stats = categoryData[itemName];
      const mrValues: number[] = [];
      for (let i = 0; i <= 36; i++) {
        mrValues.push(stats[i.toString()] || 0);
      }

      // Filter out items with no usage to avoid noise
      if (stats["ALL"] > 0) {
        items.push({
          global: stats["ALL"],
          mr: mrValues,
        });
      }
    }
  }

  console.log(`Analyzing ${items.length} items to discover MR weights...`);

  // We have a system of linear equations:
  // global_i = sum_j (weight_j * mr_i_j)
  // We want to find weights that minimize the squared error.
  // This is a least squares problem: A * w = b
  // where A is [items x 37] matrix of MR usages, w is [37 x 1] vector of weights, b is [items x 1] vector of global usages.

  // Since we don't want to pull in heavy math libraries if possible,
  // and we have a lot of data points (thousands) for 37 variables,
  // we can use a simple gradient descent or just a basic iterative solver.

  const weights = new Array(37).fill(1 / 37);
  const learningRate = 0.1;
  const iterations = 1_000_000;

  for (let iter = 0; iter < iterations; iter++) {
    const gradients = new Array(37).fill(0);
    let totalError = 0;

    for (const item of items) {
      let prediction = 0;
      for (let i = 0; i <= 36; i++) {
        prediction += weights[i] * item.mr[i];
      }
      const error = prediction - item.global;
      totalError += error * error;

      for (let i = 0; i <= 36; i++) {
        gradients[i] += 2 * error * item.mr[i];
      }
    }

    // Update weights with gradients
    for (let i = 0; i <= 36; i++) {
      weights[i] -= (learningRate * gradients[i]) / items.length;
      // Weights must be non-negative
      if (weights[i] < 0) weights[i] = 0;
    }

    // Normalize weights to sum to 1
    const sum = weights.reduce((a, b) => a + b, 0);
    for (let i = 0; i <= 36; i++) {
      weights[i] /= sum;
    }

    if (iter % 500 === 0) {
      console.log(
        `Iteration ${iter}, Avg Error: ${Math.sqrt(totalError / items.length)}`,
      );
    }
  }

  console.log("Weights discovered successfully.");

  const output = `/**
 * Discovered weights for each Mastery Rank (0-36).
 * Calculated by solving global_usage = sum(weight_i * usage_at_mr_i)
 * Generated by scripts/solve_weights.ts
 */
export const MR_WEIGHTS: Record<number, number> = {
${weights.map((w, i) => `  ${i}: ${w.toFixed(10)}`).join(",\n")}
};

export const TOTAL_WEIGHT = 1.0;
`;

  // Ensure directory exists
  const dir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`Weights written to ${OUTPUT_PATH}`);
}

solveWeights();
